
camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_ENGINE_ADMIN_USER}
      password: ${CAMUNDA_ENGINE_ADMIN_PASSWORD}
    authorization:
      enabled: true
    database:
      schema-update: ${CAMUNDA_ENGINE_DB_SCHEMA_UPDATE_CONFIG}
      type:  ${CAMUNDA_ENGINE_DB_TYPE}
      schema-name: ${CAMUNDA_ENGINE_DB_SCHEMA:camunda}
      table-prefix: ${CAMUNDA_ENGINE_DB_SCHEMA:camunda}.
      history-level: NONE
    filter:
      create: All
    generic-properties.properties:
      deserialization-type-validation-enabled: true
      deserialization-allowed-packages:
      deserialization-allowed-classes:
      enable-password-policy: true
    webapp:
      csrf:
        enable-same-site-cookie: true
        same-site-cookie-option: STRICT
      header-security:
        hsts-disabled: false

spring:
  application:
    name: atm-layer-workflow-engine
  datasource:
    url: ${CAMUNDA_ENGINE_DB_BASE_URL}/${CAMUNDA_ENGINE_DB_NAME}?currentSchema=${CAMUNDA_ENGINE_DB_SCHEMA:camunda}
    driver-class-name: ${CAMUNDA_ENGINE_DB_DRIVER}
    username: ${CAMUNDA_ENGINE_DB_USERNAME}
    password: ${CAMUNDA_ENGINE_DB_PASSWORD}
  web.resources:
    static-locations: NULL


tracing:
  url: ${TRACING_ENDPOINT:http://localhost:4317}

management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8080
