camunda.bpm:
  admin-user:
    id: ${CAMUNDA_ENGINE_ADMIN_USER}
    password: ${CAMUNDA_ENGINE_ADMIN_PASSWORD}
  database:
    schema-update: ${CAMUNDA_ENGINE_DB_SCHEMA_UPDATE_CONFIG}
    type: ${CAMUNDA_ENGINE_DB_TYPE}
    schema-name: ${CAMUNDA_ENGINE_DB_SCHEMA:camunda}
    table-prefix: ${CAMUNDA_ENGINE_DB_SCHEMA:camunda}.
  history-level: NONE
  job-execution:
    core-pool-size: 10
    max-pool-size: 50
    enabled: true
    deployment-aware: false
    keep-alive-seconds: 0
    lock-time-in-millis: 300000
    max-jobs-per-acquisition: 3
    queue-capacity: 3
    wait-time-in-millis: 5000
    max-wait: 60000
    backoff-time-in-millis: 0
    max-backoff: 0
    backoff-decrease-threshold: 100
    wait-increase-factor: 2

  filter:
    create: All
  webapp:
    csrf:
      enable-same-site-cookie: true
      same-site-cookie-option: STRICT
    header-security:
      hsts-disabled: false
  generic-properties.properties:
    deserialization-type-validation-enabled: true
    deserialization-allowed-packages:
    deserialization-allowed-classes:
    enable-password-policy: true

logging:
  level:
    root: ${CAMUNDA_ENGINE_LOG_LEVEL_ROOT:INFO}

spring:
  application:
    name: atm-layer-workflow-engine
  datasource:
    url: ${CAMUNDA_ENGINE_DB_BASE_URL}/${CAMUNDA_ENGINE_DB_NAME}?currentSchema=${CAMUNDA_ENGINE_DB_SCHEMA:camunda}
    driver-class-name: ${CAMUNDA_ENGINE_DB_DRIVER}
    username: ${CAMUNDA_ENGINE_DB_USERNAME}
    password: ${CAMUNDA_ENGINE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 50

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


spring.web.resources:
  static-locations: NULL

tracing:
  url: ${TRACING_ENDPOINT}

external:
  api:
    adapter:
      url: ${MIL_ADAPTER_BASE_URL:http://pagopa-uat-atm-layer-mil-adapter.pagopa.svc.cluster.local:8080}/externalcall

management:
  tracing:
    sampling:
      probability: 1.0

