camunda.bpm:
  admin-user:
    id: ${CAMUNDA_ENGINE_ADMIN_USER}
    password: ${CAMUNDA_ENGINE_ADMIN_PASSWORD}
  database:
    schema-update: ${CAMUNDA_ENGINE_DB_SCHEMA_UPDATE_CONFIG}
    type: ${CAMUNDA_ENGINE_DB_TYPE}
    schema-name: ${CAMUNDA_ENGINE_DB_SCHEMA:camunda}
    table-prefix: ${CAMUNDA_ENGINE_DB_SCHEMA:camunda}.
  history-level: NONE
  filter:
    create: All
  webapp:
    csrf:
      enable-same-site-cookie: true
      same-site-cookie-option: STRICT
    header-security:
      hsts-disabled: false
  generic-properties.properties:
    deserialization-type-validation-enabled: true
    deserialization-allowed-packages:
    deserialization-allowed-classes:
    enable-password-policy: true

logging:
  level:
    root: ${CAMUNDA_ENGINE_LOG_LEVEL_ROOT:INFO}

spring:
  application:
    name: atm-layer-workflow-engine
  datasource:
    url: ${CAMUNDA_ENGINE_DB_BASE_URL}/${CAMUNDA_ENGINE_DB_NAME}?currentSchema=${CAMUNDA_ENGINE_DB_SCHEMA:camunda}
    driver-class-name: ${CAMUNDA_ENGINE_DB_DRIVER}
    username: ${CAMUNDA_ENGINE_DB_USERNAME}
    password: ${CAMUNDA_ENGINE_DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

spring.web.resources:
  static-locations: NULL

tracing:
  url: ${TRACING_ENDPOINT}

engine-notification:
  wait-status:
    callback-base-path: ${CAMUNDA_ENGINE_WAIT_STATUS_NOTIFICATION_CALLBACK_BASE_PATH}
    enabled: ${CAMUNDA_ENGINE_WAIT_STATUS_NOTIFICATION_ENABLED:false}

management:
  tracing:
    sampling:
      probability: 1.0

