{{- $fullName := include "atm-layer-wf-engine.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "atm-layer-wf-engine.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.general.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "atm-layer-wf-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or (.Values.recreatePods) (.Values.podAnnotations) }}
      annotations:
        {{- if (.Values.recreatePods) }}
        created: {{ now }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "atm-layer-wf-engine.selectorLabels" . | nindent 8 }}
        {{- include "atm-layer-wf-engine.customLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atm-layer-wf-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 6 }}
      {{- end }}
      containers:
      {{- if .Values.extraContainers }}
      {{- with tpl (toYaml .Values.extraContainers) . }}
        {{ . | nindent 8 }}
      {{- end }}
      {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          {{ if .Values.image.command -}}
          command: {{ .Values.image.command }}
          {{- end }}
          {{- if .Values.image.args }}
          args:
            {{- toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CAMUNDA_ENGINE_LOG_LEVEL_ROOT
              value: "{{ .Values.general.log_level }}"
            - name: JMX_PROMETHEUS
              value: "{{ .Values.metrics.enabled }}"
            - name: CAMUNDA_ENGINE_DB_DRIVER
              value: "{{ .Values.database.driver }}"
            - name: CAMUNDA_ENGINE_DB_BASE_URL
              value: "{{ .Values.database.url }}"
            - name: CAMUNDA_ENGINE_DB_NAME
              value: "{{ .Values.database.db_name }}"
            - name: CAMUNDA_ENGINE_DB_TYPE
              value: "{{ .Values.database.db_type }}"
            - name: CAMUNDA_ENGINE_DB_SCHEMA_UPDATE_CONFIG
              value: "{{ .Values.database.db_schema_update_config }}"
            - name: CAMUNDA_ENGINE_DB_SCHEMA
              value: "{{ .Values.database.schema }}"
            {{- if .Values.database.credentialsSecretEnabled }}
            - name: CAMUNDA_ENGINE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.credentialsSecretName | default $fullName }}
                  key: {{ .Values.database.credentialsSecretKeys.username }}
            - name: CAMUNDA_ENGINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.credentialsSecretName | default $fullName }}
                  key: {{ .Values.database.credentialsSecretKeys.password }}
            {{- end }}
            {{- if .Values.webuser.credentialsSecretEnabled }}
            - name: CAMUNDA_ENGINE_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webuser.credentialsSecretName | default $fullName }}
                  key: {{ .Values.webuser.credentialsSecretKeys.username }}
            - name: CAMUNDA_ENGINE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webuser.credentialsSecretName | default $fullName }}
                  key: {{ .Values.webuser.credentialsSecretKeys.password }}
            {{- end }}
          {{- if .Values.extraEnvs }}
          {{- with tpl (toYaml .Values.extraEnvs) . }}
            {{ . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
            {{- if .Values.metrics.enabled }}
            - name: {{ .Values.metrics.service.portName }}
              containerPort: {{ .Values.metrics.service.port }}
              protocol: {{ .Values.metrics.service.protocol }}
            {{- end }}
          {{ if .Values.startupProbe.enabled -}}
          startupProbe:
            {{- toYaml .Values.startupProbe.config | nindent 12 }}
          {{- end }}
          {{ if .Values.readinessProbe.enabled -}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.config | nindent 12 }}
          {{- end }}
          {{ if .Values.livenessProbe.enabled -}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.config | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if eq (include "atm-layer-wf-engine.withVolumes" .) "true" -}}
          volumeMounts:
             {{- if eq (include "atm-layer-wf-engine.h2DatabaseIsUsed" .) "true" }}
             - name: {{ $fullName }}-database-h2
               mountPath: /camunda/camunda-h2-dbs
             {{- end }}
             {{- if .Values.configmap.enabled }}
            - name: config-volume
              mountPath: /camunda/configuration/production.yml
              subPath: production.yml
             {{- end }}
            {{- if .Values.extraVolumeMounts }}
              {{- tpl (toYaml .Values.extraVolumeMounts) . | nindent 12 }}
            {{- end }}
            - name: secrets-store-inline-1
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: secrets-store-inline-2
              mountPath: "/mnt/secrets-store"
              readOnly: true
          {{- end }}
      {{ if eq (include "atm-layer-wf-engine.withVolumes" .) "true" -}}
      volumes:
         {{- if eq (include "atm-layer-wf-engine.h2DatabaseIsUsed" .) "true" }}
         - name: {{ $fullName }}-database-h2
           persistentVolumeClaim:
             claimName: {{ $fullName }}-database-h2
         {{- end }}
         {{- if .Values.configmap.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "atm-layer-wf-engine.fullname" . }}
        {{- end -}}
        {{- if .Values.extraVolumes }}
          {{- tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}
        - name: secrets-store-inline-1
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true 
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClass.name }}
        - name: secrets-store-inline-2
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true 
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClass.name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
