name: Coverage on PR

on:
  pull_request:

jobs:
  pr_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Setup JDK
        uses: graalvm/setup-graalvm@2f25c0caae5b220866f732832d5e3e29ff493338 # v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test execution
        run: |
          mvn test

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@7a334255fbce42f385d7567c25d986a9c62e2971
        with:
          paths: target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          title: jacoco
          update-comment: true

      - name: Fail PR if overall coverage is less than 70%
        if: ${{ steps.jacoco.outputs.coverage-overall < 70.0 }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 70%!')
